# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            "Chloe"
tagline:          'A writer person'
description:      'I am a writer based in Melbourne, Australia.'
url:              https://thewonglab.github.io/chloewrites_
baseurl:          /chloewrites_

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://thewonglab.github.io/chloewrites_
